# Generated by Django 4.2.6 on 2023-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_tag_order_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='App.tag'),
        ),
    ]
